ДЗ 4 раздел
htmlacademy-javascript/1833907-kekstagram-28 pull request #3
Opened 2023-03-12 16:41 UTC by SafAlyona

2023-03-13 07:33 UTC, Jahonta requested changes

2023-03-13 07:33 UTC, Jahonta commented on js/main.js
> +  avatar: `img/avatar-${getRandomInteger(1,7)}.svg`,
Я тебя обманула. Верхняя граница всё-таки включается. А значит,  тут должно быть 6. А ниже - не 201, а 200

2023-03-13 07:33 UTC, Jahonta commented on js/main.js
> +  message: getRandomArrayElement(MESSAGES),
По условию домашки сообщение может состоять либо из одного, либо из двух элементов массива.

2023-03-13 07:33 UTC, Jahonta commented on js/main.js
> +}
Давай для тренировки (и единообразия) перепишем эти две функции на стрелочный синтаксис

2023-03-13 07:33 UTC, Jahonta commented on js/main.js
> +const generateObjects = () => Array.from({length: 25}, generateObject);
Предлагаю для тренировки вынести все ,"магические значения" в отдельные константы. Магическими называют такие значения в коде, происхождение которых не очевидно.
Например, вот тут у нас есть число 25. Может возникнуть вопрос, почему 25? Если записать его в константу OBJECT_COUNT (имя примерное, выбирай сама) и использовать в коде уже её, то станет понятно, что это значение пришло извне, из ТЗ.

Пробегись по коду домашки и вынеси всё, что можешь.

Это критерий Д19, он дополнительный, но я всё же настоятельно рекомендую его придерживаться - тем самым облегчишь жизнь и себе, и всем, кто будет работать с твоим кодом (я, например...)))

2023-03-13 07:33 UTC, Jahonta commented on js/main.js
> +  avatar: `img/avatar-${getRandomInteger(1,7)}.svg`,
Косметическое пожелание. Мы обычно (и ты ты тоже в других местах) ставишь пробелы между параметрами функции. Здесь его тоже следует добавить

2023-03-13 07:33 UTC, Jahonta commented on js/main.js
> +const generateId = createIdGenerator();
Первую функцию ты назвала `generatePhotoId`, может, тогда и тут по тому же принципу укажешь, айдишники для какой сущности будут генерироваться?

2023-03-14 05:34 UTC, Jahonta commented on js/main.js
> +const MAX_COMMENTS_ID = 25;
Это ведь не айдишники, а просто количество

2023-03-14 05:38 UTC, Jahonta commented on js/main.js
> +};
Название функции должно начинаться с глагола. В данном случае у тебя существительное "количество комментов". Что, помимо прочего, не соответсвует тому, что делает эта функция.

Ну и предлагаю на созвоне сегодня посмотреть, как можно упростить и условие, и саму функцию.

Но ты молодец! Разобралась, написала. Рафакторинг - это уже косметическое

2023-03-14 05:38 UTC, Jahonta commented on js/main.js
> +};
Молодец!

2023-03-14 05:39 UTC, Jahonta commented on index.html
> +  <script src="js/functions.js" type="module"></script>
А это зачем?

2023-03-14 05:40 UTC, Jahonta commented on js/main.js
> +const generateObjects = () => Array.from({length: 25}, generateObject);
Тут бы тоже константу..

2023-03-14 06:36 UTC, merged

2023-03-14 11:32 UTC, SafAlyona commented on index.html
> +  <script src="js/functions.js" type="module"></script>
а это я на будущее сделала и забыла)